# <span style="color:#bce35b;font-size:35px"><b>Week 3 & 4</b></span>
<!-- # <span style="color:#bce35b;font-size:35px">Title<b>Title</b></span> -->
<!-- # <span style="color:#bce35b">H1</span> -->
<!-- ## <span style="color:#ae8bd5">H2</span> -->
<!-- ### <span style="color:#9c4957">H3</span> -->
<!-- #### <span style="color:white">H4</span> -->

<span style="color:#8c8c8c">Patrick Weatherford</span>

[Green]: <> (#bce35b)
[Purple]: <> (#ae8bd5)
[Coral]: <> (#9c4957)
[Grey]: <> (#8c8c8c)

***
***

Importing libraries

In [4]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import os
import requests
from collections import deque as deq
from itertools import permutations, dropwhile, zip_longest


## import custom config file with keys and change working directory
class_path = os.path.expanduser('~') + '\\OneDrive - Bellevue University\\Bellevue_University\\DSC 540 - Data Preparation'
bu_path = os.path.expanduser('~') + '\\OneDrive - Bellevue University\\Bellevue_University'
os.chdir(bu_path); import config; os.chdir(class_path)


## matplotlib default settings
plt.style.use('dark_background')
mpl.rcParams.update({'lines.linewidth':3})
mpl.rcParams.update({'axes.labelsize':14})
mpl.rcParams.update({'axes.titlesize':16})
mpl.rcParams.update({'axes.titleweight':'bold'})
mpl.rcParams.update({'figure.autolayout':True})
mpl.rcParams.update({'axes.grid':True, 'grid.color':'#424242', 'grid.linestyle':'--'})


In [5]:
## see list of current settings
# plt.rcParams.keys()

<br>
Instantiating random number generator

In [6]:
rng_seed = 777
rng = np.random.default_rng(rng_seed)

<br>

***

# <span style="color:#bce35b">Book Activities</span>
<!-- # <span style="color:#bce35b;font-size:35px">Title<b>Title</b></span> -->
<!-- # <span style="color:#bce35b">H1</span> -->
<!-- ## <span style="color:#ae8bd5">H2</span> -->
<!-- ### <span style="color:#9c4957">H3</span> -->
<!-- #### <span style="color:white">H4</span> -->

<!-- <span style="color:#8c8c8c">Patrick Weatherford</span> -->

[Green]: <> (#bce35b)
[Purple]: <> (#ae8bd5)
[Coral]: <> (#9c4957)
[Grey]: <> (#8c8c8c)

<br>


## <span style="color:#ae8bd5">Activity 5</span>
<!-- # <span style="color:#bce35b;font-size:35px">Title<b>Title</b></span> -->
<!-- # <span style="color:#bce35b">H1</span> -->
<!-- ## <span style="color:#ae8bd5">H2</span> -->
<!-- ### <span style="color:#9c4957">H3</span> -->
<!-- #### <span style="color:white">H4</span> -->

<!-- <span style="color:#8c8c8c">Patrick Weatherford</span> -->

[Green]: <> (#bce35b)
[Purple]: <> (#ae8bd5)
[Coral]: <> (#9c4957)
[Grey]: <> (#8c8c8c)

Boston Housing data set.

- CRIM     per capita crime rate by town
- ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
- INDUS    proportion of non-retail business acres per town
- CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
- NOX      nitric oxides concentration (parts per 10 million)
- RM       average number of rooms per dwelling
- AGE      proportion of owner-occupied units built prior to 1940
- DIS      weighted distances to five Boston employment centres
- RAD      index of accessibility to radial highways
- TAX      full-value property-tax rate per \$10,000
- PTRATIO  pupil-teacher ratio by town
- B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
- LSTAT    % lower status of the population
- MEDV     Median value of owner-occupied homes in $1000's

In [46]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :3]])
labels = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV']

bost_df = pd.DataFrame(data, columns=labels)

In [47]:
bost_df.head(10)

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575   65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421   78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185   61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998   45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147   54.2  6.0622  3.0  222.0   
5  0.02985   0.0   2.18   0.0  0.458  6.430   58.7  6.0622  3.0  222.0   
6  0.08829  12.5   7.87   0.0  0.524  6.012   66.6  5.5605  5.0  311.0   
7  0.14455  12.5   7.87   0.0  0.524  6.172   96.1  5.9505  5.0  311.0   
8  0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
9  0.17004  12.5   7.87   0.0  0.524  6.004   85.9  6.5921  5.0  311.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2  
5     18.7  394.12   5.21  28.7  
6     15.2  395.60  12.43  22.9  
7     15.2  396.90  19.15  27.1  
8     15.2  386.63  29.93  16.5  
9     15.2  386.71  17.10  18.9

<br>


## <span style="color:#ae8bd5">Activity 6</span>
<!-- # <span style="color:#bce35b;font-size:35px">Title<b>Title</b></span> -->
<!-- # <span style="color:#bce35b">H1</span> -->
<!-- ## <span style="color:#ae8bd5">H2</span> -->
<!-- ### <span style="color:#9c4957">H3</span> -->
<!-- #### <span style="color:white">H4</span> -->

<!-- <span style="color:#8c8c8c">Patrick Weatherford</span> -->

[Green]: <> (#bce35b)
[Purple]: <> (#ae8bd5)
[Coral]: <> (#9c4957)
[Grey]: <> (#8c8c8c)

<br>

***

# <span style="color:#bce35b">Series and Basic Arithmetic</span>
<!-- # <span style="color:#bce35b;font-size:35px">Title<b>Title</b></span> -->
<!-- # <span style="color:#bce35b">H1</span> -->
<!-- ## <span style="color:#ae8bd5">H2</span> -->
<!-- ### <span style="color:#9c4957">H3</span> -->
<!-- #### <span style="color:white">H4</span> -->

<!-- <span style="color:#8c8c8c">Patrick Weatherford</span> -->

[Green]: <> (#bce35b)
[Purple]: <> (#ae8bd5)
[Coral]: <> (#9c4957)
[Grey]: <> (#8c8c8c)

<br><br>

Below code is for practice only

In [7]:
np.arange(start=1, stop=20, step=2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
np.arange(start=30, stop=-1, step=-2)

array([30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [9]:
np.linspace(start=1, stop=10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [10]:
np.linspace(start=30, stop=0, num=20)

array([30.        , 28.42105263, 26.84210526, 25.26315789, 23.68421053,
       22.10526316, 20.52631579, 18.94736842, 17.36842105, 15.78947368,
       14.21052632, 12.63157895, 11.05263158,  9.47368421,  7.89473684,
        6.31578947,  4.73684211,  3.15789474,  1.57894737,  0.        ])

In [11]:
a1 = rng.integers(1,100,30)

a1

array([90, 61, 35, 38, 10, 60, 45, 96, 32, 20, 32, 34, 35, 57, 42, 54, 50,
       73,  6, 43, 94,  6, 61, 17, 63, 75, 51, 68, 53, 70], dtype=int64)

In [12]:
a1_re = a1.reshape(2,3,5)
a1_re

array([[[90, 61, 35, 38, 10],
        [60, 45, 96, 32, 20],
        [32, 34, 35, 57, 42]],

       [[54, 50, 73,  6, 43],
        [94,  6, 61, 17, 63],
        [75, 51, 68, 53, 70]]], dtype=int64)

In [13]:
a1_re[1,0,3]
## index[1] in axis 0
## index[0] in axis 1
## index[3] in axis 2

6

In [14]:
a1_re.size, a1_re.shape, a1_re.ndim

(30, (2, 3, 5), 3)

In [15]:
a1_rav = a1_re.ravel()
a1_rav

array([90, 61, 35, 38, 10, 60, 45, 96, 32, 20, 32, 34, 35, 57, 42, 54, 50,
       73,  6, 43, 94,  6, 61, 17, 63, 75, 51, 68, 53, 70], dtype=int64)

In [16]:
a2 = rng.integers(1,10,20).reshape(4,5)
a2

array([[4, 1, 1, 1, 4],
       [9, 6, 4, 4, 1],
       [3, 2, 3, 5, 8],
       [3, 6, 1, 8, 8]], dtype=int64)

In [17]:
df = pd.DataFrame(a2)
df

0  1  2  3  4
0  4  1  1  1  4
1  9  6  4  4  1
2  3  2  3  5  8
3  3  6  1  8  8

In [18]:
df1 = df.drop(0, axis=1)
df1

1  2  3  4
0  1  1  1  4
1  6  4  4  1
2  2  3  5  8
3  6  1  8  8

In [19]:
rng.binomial(n=8, p=.6, size=10)

array([6, 6, 6, 3, 4, 4, 7, 6, 6, 6], dtype=int64)